name: ml
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - jupyterlab
  - matplotlib
  - torchvision
  - torchaudio
  - cpuonly
  - pytorch
  - scikit-learn
  - h5py
  - pip
